/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as ShadeGeneratorImport } from './routes/shade-generator'
import { Route as GradientImport } from './routes/gradient'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const ShadeGeneratorRoute = ShadeGeneratorImport.update({
  id: '/shade-generator',
  path: '/shade-generator',
  getParentRoute: () => rootRoute,
} as any)

const GradientRoute = GradientImport.update({
  id: '/gradient',
  path: '/gradient',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/gradient': {
      id: '/gradient'
      path: '/gradient'
      fullPath: '/gradient'
      preLoaderRoute: typeof GradientImport
      parentRoute: typeof rootRoute
    }
    '/shade-generator': {
      id: '/shade-generator'
      path: '/shade-generator'
      fullPath: '/shade-generator'
      preLoaderRoute: typeof ShadeGeneratorImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/gradient': typeof GradientRoute
  '/shade-generator': typeof ShadeGeneratorRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/gradient': typeof GradientRoute
  '/shade-generator': typeof ShadeGeneratorRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/gradient': typeof GradientRoute
  '/shade-generator': typeof ShadeGeneratorRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/gradient' | '/shade-generator'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/gradient' | '/shade-generator'
  id: '__root__' | '/' | '/gradient' | '/shade-generator'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GradientRoute: typeof GradientRoute
  ShadeGeneratorRoute: typeof ShadeGeneratorRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GradientRoute: GradientRoute,
  ShadeGeneratorRoute: ShadeGeneratorRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/gradient",
        "/shade-generator"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/gradient": {
      "filePath": "gradient.tsx"
    },
    "/shade-generator": {
      "filePath": "shade-generator.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
