/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as OklchDemoImport } from './routes/oklch-demo'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const OklchDemoRoute = OklchDemoImport.update({
  id: '/oklch-demo',
  path: '/oklch-demo',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/oklch-demo': {
      id: '/oklch-demo'
      path: '/oklch-demo'
      fullPath: '/oklch-demo'
      preLoaderRoute: typeof OklchDemoImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/oklch-demo': typeof OklchDemoRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/oklch-demo': typeof OklchDemoRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/oklch-demo': typeof OklchDemoRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/oklch-demo'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/oklch-demo'
  id: '__root__' | '/' | '/oklch-demo'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  OklchDemoRoute: typeof OklchDemoRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  OklchDemoRoute: OklchDemoRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/oklch-demo"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/oklch-demo": {
      "filePath": "oklch-demo.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
